# This environment.yml file would create an environment called fp2
# The newly created environment would be installed inside the ~/miniconda3/envs/ directory, unless we specified a different path using --prefix

name: fp2
channels:
- conda-forge
dependencies:
- python=3.8
- pre-commit=2.16
- matplotlib=3.5
- numpy=1.21
- pandas=1.3
- pip=21.3
- pytest=6.2
- requests=2.26
- seaborn=0.11
- scipy=1.7
- scikit-learn=1.0
- statsmodels=0.13
- urllib3=1.26
- pycaret=2.3
- xgboost=1.5
- imageio=2.13
- dagit=0.13
- dagster=0.13
