# This environment.yml file would create an environment called fp2
# with the most current and mutually compatible versions of the listed packages (including all required dependencies). 
# The newly created environment would be installed inside the ~/miniconda3/envs/ directory, unless we specified a different path using --prefix

name: fp2
channels:
- conda-forge
dependencies:
- python=3.8
- pre-commit
- jupyterlab
- ipykernel
- ipywidgets
- dask
- ipython
- joblib
- jupyter
- matplotlib
- notebook
- numpy
- openblas
- pandas
- patsy
- pip
- psycopg2
- pyarrow
- pytest
- pyyaml
- requests
- seaborn
- scipy
- scikit-learn
- statsmodels
- urllib3
