name: fp2
channels:
- conda-forge
dependencies:
- python=3.8
- pre-commit
- jupyterlab
- ipykernel
- ipywidgets
- dask
- ipython
- joblib
- jupyter
- matplotlib
- notebook
- numpy
- openblas
- pandas
- patsy
- pip
- psycopg2
- pyarrow
- pytest
- pyyaml
- requests
- seaborn
- scipy
- scikit-learn
- statsmodels
- urllib3
